const ARCGIS_APP_API_KEY = "ARCGIS_APP_API_KEY"
const ARCGIS_APP_CLIENT_ID = "ARCGIS_APP_CLIENT_ID"
const ARCGIS_APP_CLIENT_SECRET= "ARCGIS_APP_CLIENT_SECRET"
const ARCGIS_APP_TOKEN= "ARCGIS_APP_TOKEN"

export {ARCGIS_APP_API_KEY, 
    ARCGIS_APP_CLIENT_ID, 
    ARCGIS_APP_CLIENT_SECRET,
    ARCGIS_APP_TOKEN};